compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmPublishRegistry: https://registry.npmjs.org
npmRegistryServer: https://registry.npmjs.org
